import 'package:film_maker/l10n/app_strings.dart';

/// Grouping used by the sticker picker UI.
enum StickerCategory { charms, hearts, keepsakes, wedding }

extension StickerCategoryX on StickerCategory {
  String get label => switch (this) {
        StickerCategory.charms    => L10n.s.stickerCatCharms,
        StickerCategory.hearts    => L10n.s.stickerCatHearts,
        StickerCategory.keepsakes => L10n.s.stickerCatKeepsakes,
        StickerCategory.wedding   => L10n.s.stickerCatWedding,
      };
}

/// A curated set of photo-realistic decorative stickers. Each is a pre-cut
/// (background-removed) PNG asset under assets/stickers/. Rendered as an image
/// so it looks identical in the editor and the export.
enum StickerKind {
  star,
  moon,
  cloud,
  diamond,
  clover,
  shell,
  key,
  crystalBall,
  paperPlane,
  balloon,
  featherGray,
  starSilver,
  leafSprig,
  tag,
  daisy,
  button,
  puzzle,
  paperclip,
  house,
  sun,
  heartWhite,
  heartCrystal,
  bowPink,
  heartGoldOutline,
  heartPink,
  heartGold,
  heartCloud,
  heartGlass,
  heartPearl,
  heartYarn,
  heartCandle,
  heartLock,
  heartFoil,
  heartWreath,
  heartOrigami,
  heartChoco,
  camera,
  teddyBear,
  tulips,
  books,
  mug,
  memoryJar,
  plant,
  alarmClock,
  basket,
  calendar,
  lantern,
  puppy,
  teaCup,
  violin,
  driedFlowers,
  strawHat,
  bowSilver,
  rose,
  pearlEarrings,
  candle,
  bouquet,
  giftBox,
  envelope,
  featherWhite,
  rings,
  perfume,
  pearlBracelet,
  champagne,
  cake,
  goblet,
  heels,
  frame,
}

extension StickerKindX on StickerKind {
  /// Bundled cut-out PNG asset for this sticker.
  String get assetPath => switch (this) {
        StickerKind.star => 'assets/stickers/star.png',
        StickerKind.moon => 'assets/stickers/moon.png',
        StickerKind.cloud => 'assets/stickers/cloud.png',
        StickerKind.diamond => 'assets/stickers/diamond.png',
        StickerKind.clover => 'assets/stickers/clover.png',
        StickerKind.shell => 'assets/stickers/shell.png',
        StickerKind.key => 'assets/stickers/key.png',
        StickerKind.crystalBall => 'assets/stickers/crystal_ball.png',
        StickerKind.paperPlane => 'assets/stickers/paper_plane.png',
        StickerKind.balloon => 'assets/stickers/balloon.png',
        StickerKind.featherGray => 'assets/stickers/feather_gray.png',
        StickerKind.starSilver => 'assets/stickers/star_silver.png',
        StickerKind.leafSprig => 'assets/stickers/leaf_sprig.png',
        StickerKind.tag => 'assets/stickers/tag.png',
        StickerKind.daisy => 'assets/stickers/daisy.png',
        StickerKind.button => 'assets/stickers/button.png',
        StickerKind.puzzle => 'assets/stickers/puzzle.png',
        StickerKind.paperclip => 'assets/stickers/paperclip.png',
        StickerKind.house => 'assets/stickers/house.png',
        StickerKind.sun => 'assets/stickers/sun.png',
        StickerKind.heartWhite => 'assets/stickers/heart_white.png',
        StickerKind.heartCrystal => 'assets/stickers/heart_crystal.png',
        StickerKind.bowPink => 'assets/stickers/bow_pink.png',
        StickerKind.heartGoldOutline => 'assets/stickers/heart_gold_outline.png',
        StickerKind.heartPink => 'assets/stickers/heart_pink.png',
        StickerKind.heartGold => 'assets/stickers/heart_gold.png',
        StickerKind.heartCloud => 'assets/stickers/heart_cloud.png',
        StickerKind.heartGlass => 'assets/stickers/heart_glass.png',
        StickerKind.heartPearl => 'assets/stickers/heart_pearl.png',
        StickerKind.heartYarn => 'assets/stickers/heart_yarn.png',
        StickerKind.heartCandle => 'assets/stickers/heart_candle.png',
        StickerKind.heartLock => 'assets/stickers/heart_lock.png',
        StickerKind.heartFoil => 'assets/stickers/heart_foil.png',
        StickerKind.heartWreath => 'assets/stickers/heart_wreath.png',
        StickerKind.heartOrigami => 'assets/stickers/heart_origami.png',
        StickerKind.heartChoco => 'assets/stickers/heart_choco.png',
        StickerKind.camera => 'assets/stickers/camera.png',
        StickerKind.teddyBear => 'assets/stickers/teddy_bear.png',
        StickerKind.tulips => 'assets/stickers/tulips.png',
        StickerKind.books => 'assets/stickers/books.png',
        StickerKind.mug => 'assets/stickers/mug.png',
        StickerKind.memoryJar => 'assets/stickers/memory_jar.png',
        StickerKind.plant => 'assets/stickers/plant.png',
        StickerKind.alarmClock => 'assets/stickers/alarm_clock.png',
        StickerKind.basket => 'assets/stickers/basket.png',
        StickerKind.calendar => 'assets/stickers/calendar.png',
        StickerKind.lantern => 'assets/stickers/lantern.png',
        StickerKind.puppy => 'assets/stickers/puppy.png',
        StickerKind.teaCup => 'assets/stickers/tea_cup.png',
        StickerKind.violin => 'assets/stickers/violin.png',
        StickerKind.driedFlowers => 'assets/stickers/dried_flowers.png',
        StickerKind.strawHat => 'assets/stickers/straw_hat.png',
        StickerKind.bowSilver => 'assets/stickers/bow_silver.png',
        StickerKind.rose => 'assets/stickers/rose.png',
        StickerKind.pearlEarrings => 'assets/stickers/pearl_earrings.png',
        StickerKind.candle => 'assets/stickers/candle.png',
        StickerKind.bouquet => 'assets/stickers/bouquet.png',
        StickerKind.giftBox => 'assets/stickers/gift_box.png',
        StickerKind.envelope => 'assets/stickers/envelope.png',
        StickerKind.featherWhite => 'assets/stickers/feather_white.png',
        StickerKind.rings => 'assets/stickers/rings.png',
        StickerKind.perfume => 'assets/stickers/perfume.png',
        StickerKind.pearlBracelet => 'assets/stickers/pearl_bracelet.png',
        StickerKind.champagne => 'assets/stickers/champagne.png',
        StickerKind.cake => 'assets/stickers/cake.png',
        StickerKind.goblet => 'assets/stickers/goblet.png',
        StickerKind.heels => 'assets/stickers/heels.png',
        StickerKind.frame => 'assets/stickers/frame.png',
      };

  /// Category used to group stickers in the picker.
  StickerCategory get category => switch (this) {
        StickerKind.star => StickerCategory.charms,
        StickerKind.moon => StickerCategory.charms,
        StickerKind.cloud => StickerCategory.charms,
        StickerKind.diamond => StickerCategory.charms,
        StickerKind.clover => StickerCategory.charms,
        StickerKind.shell => StickerCategory.charms,
        StickerKind.key => StickerCategory.charms,
        StickerKind.crystalBall => StickerCategory.charms,
        StickerKind.paperPlane => StickerCategory.charms,
        StickerKind.balloon => StickerCategory.charms,
        StickerKind.featherGray => StickerCategory.charms,
        StickerKind.starSilver => StickerCategory.charms,
        StickerKind.leafSprig => StickerCategory.charms,
        StickerKind.tag => StickerCategory.charms,
        StickerKind.daisy => StickerCategory.charms,
        StickerKind.button => StickerCategory.charms,
        StickerKind.puzzle => StickerCategory.charms,
        StickerKind.paperclip => StickerCategory.charms,
        StickerKind.house => StickerCategory.charms,
        StickerKind.sun => StickerCategory.charms,
        StickerKind.heartWhite => StickerCategory.hearts,
        StickerKind.heartCrystal => StickerCategory.hearts,
        StickerKind.bowPink => StickerCategory.hearts,
        StickerKind.heartGoldOutline => StickerCategory.hearts,
        StickerKind.heartPink => StickerCategory.hearts,
        StickerKind.heartGold => StickerCategory.hearts,
        StickerKind.heartCloud => StickerCategory.hearts,
        StickerKind.heartGlass => StickerCategory.hearts,
        StickerKind.heartPearl => StickerCategory.hearts,
        StickerKind.heartYarn => StickerCategory.hearts,
        StickerKind.heartCandle => StickerCategory.hearts,
        StickerKind.heartLock => StickerCategory.hearts,
        StickerKind.heartFoil => StickerCategory.hearts,
        StickerKind.heartWreath => StickerCategory.hearts,
        StickerKind.heartOrigami => StickerCategory.hearts,
        StickerKind.heartChoco => StickerCategory.hearts,
        StickerKind.camera => StickerCategory.keepsakes,
        StickerKind.teddyBear => StickerCategory.keepsakes,
        StickerKind.tulips => StickerCategory.keepsakes,
        StickerKind.books => StickerCategory.keepsakes,
        StickerKind.mug => StickerCategory.keepsakes,
        StickerKind.memoryJar => StickerCategory.keepsakes,
        StickerKind.plant => StickerCategory.keepsakes,
        StickerKind.alarmClock => StickerCategory.keepsakes,
        StickerKind.basket => StickerCategory.keepsakes,
        StickerKind.calendar => StickerCategory.keepsakes,
        StickerKind.lantern => StickerCategory.keepsakes,
        StickerKind.puppy => StickerCategory.keepsakes,
        StickerKind.teaCup => StickerCategory.keepsakes,
        StickerKind.violin => StickerCategory.keepsakes,
        StickerKind.driedFlowers => StickerCategory.keepsakes,
        StickerKind.strawHat => StickerCategory.keepsakes,
        StickerKind.bowSilver => StickerCategory.wedding,
        StickerKind.rose => StickerCategory.wedding,
        StickerKind.pearlEarrings => StickerCategory.wedding,
        StickerKind.candle => StickerCategory.wedding,
        StickerKind.bouquet => StickerCategory.wedding,
        StickerKind.giftBox => StickerCategory.wedding,
        StickerKind.envelope => StickerCategory.wedding,
        StickerKind.featherWhite => StickerCategory.wedding,
        StickerKind.rings => StickerCategory.wedding,
        StickerKind.perfume => StickerCategory.wedding,
        StickerKind.pearlBracelet => StickerCategory.wedding,
        StickerKind.champagne => StickerCategory.wedding,
        StickerKind.cake => StickerCategory.wedding,
        StickerKind.goblet => StickerCategory.wedding,
        StickerKind.heels => StickerCategory.wedding,
        StickerKind.frame => StickerCategory.wedding,
      };

  /// Human-readable name.
  String get label => switch (this) {
        StickerKind.star => 'Star',
        StickerKind.moon => 'Moon',
        StickerKind.cloud => 'Cloud',
        StickerKind.diamond => 'Diamond',
        StickerKind.clover => 'Clover',
        StickerKind.shell => 'Shell',
        StickerKind.key => 'Key',
        StickerKind.crystalBall => 'Crystal Ball',
        StickerKind.paperPlane => 'Paper Plane',
        StickerKind.balloon => 'Balloon',
        StickerKind.featherGray => 'Feather Gray',
        StickerKind.starSilver => 'Star Silver',
        StickerKind.leafSprig => 'Leaf Sprig',
        StickerKind.tag => 'Tag',
        StickerKind.daisy => 'Daisy',
        StickerKind.button => 'Button',
        StickerKind.puzzle => 'Puzzle',
        StickerKind.paperclip => 'Paperclip',
        StickerKind.house => 'House',
        StickerKind.sun => 'Sun',
        StickerKind.heartWhite => 'Heart White',
        StickerKind.heartCrystal => 'Heart Crystal',
        StickerKind.bowPink => 'Bow Pink',
        StickerKind.heartGoldOutline => 'Heart Gold Outline',
        StickerKind.heartPink => 'Heart Pink',
        StickerKind.heartGold => 'Heart Gold',
        StickerKind.heartCloud => 'Heart Cloud',
        StickerKind.heartGlass => 'Heart Glass',
        StickerKind.heartPearl => 'Heart Pearl',
        StickerKind.heartYarn => 'Heart Yarn',
        StickerKind.heartCandle => 'Heart Candle',
        StickerKind.heartLock => 'Heart Lock',
        StickerKind.heartFoil => 'Heart Foil',
        StickerKind.heartWreath => 'Heart Wreath',
        StickerKind.heartOrigami => 'Heart Origami',
        StickerKind.heartChoco => 'Heart Choco',
        StickerKind.camera => 'Camera',
        StickerKind.teddyBear => 'Teddy Bear',
        StickerKind.tulips => 'Tulips',
        StickerKind.books => 'Books',
        StickerKind.mug => 'Mug',
        StickerKind.memoryJar => 'Memory Jar',
        StickerKind.plant => 'Plant',
        StickerKind.alarmClock => 'Alarm Clock',
        StickerKind.basket => 'Basket',
        StickerKind.calendar => 'Calendar',
        StickerKind.lantern => 'Lantern',
        StickerKind.puppy => 'Puppy',
        StickerKind.teaCup => 'Tea Cup',
        StickerKind.violin => 'Violin',
        StickerKind.driedFlowers => 'Dried Flowers',
        StickerKind.strawHat => 'Straw Hat',
        StickerKind.bowSilver => 'Bow Silver',
        StickerKind.rose => 'Rose',
        StickerKind.pearlEarrings => 'Pearl Earrings',
        StickerKind.candle => 'Candle',
        StickerKind.bouquet => 'Bouquet',
        StickerKind.giftBox => 'Gift Box',
        StickerKind.envelope => 'Envelope',
        StickerKind.featherWhite => 'Feather White',
        StickerKind.rings => 'Rings',
        StickerKind.perfume => 'Perfume',
        StickerKind.pearlBracelet => 'Pearl Bracelet',
        StickerKind.champagne => 'Champagne',
        StickerKind.cake => 'Cake',
        StickerKind.goblet => 'Goblet',
        StickerKind.heels => 'Heels',
        StickerKind.frame => 'Frame',
      };

  /// Natural width / height of the artwork (from the cropped asset). Used to
  /// derive the layer's height from its [StickerLayer.widthFraction].
  double get aspectRatio => switch (this) {
        StickerKind.star => 1.01,
        StickerKind.moon => 1.147,
        StickerKind.cloud => 1.288,
        StickerKind.diamond => 1.286,
        StickerKind.clover => 1.029,
        StickerKind.shell => 1.05,
        StickerKind.key => 0.431,
        StickerKind.crystalBall => 0.909,
        StickerKind.paperPlane => 1.124,
        StickerKind.balloon => 0.683,
        StickerKind.featherGray => 0.576,
        StickerKind.starSilver => 0.953,
        StickerKind.leafSprig => 0.835,
        StickerKind.tag => 0.943,
        StickerKind.daisy => 0.978,
        StickerKind.button => 0.91,
        StickerKind.puzzle => 1.012,
        StickerKind.paperclip => 0.555,
        StickerKind.house => 0.851,
        StickerKind.sun => 0.984,
        StickerKind.heartWhite => 1.043,
        StickerKind.heartCrystal => 1.041,
        StickerKind.bowPink => 0.804,
        StickerKind.heartGoldOutline => 1.107,
        StickerKind.heartPink => 1.015,
        StickerKind.heartGold => 1.104,
        StickerKind.heartCloud => 0.847,
        StickerKind.heartGlass => 1.077,
        StickerKind.heartPearl => 1.075,
        StickerKind.heartYarn => 1.154,
        StickerKind.heartCandle => 0.98,
        StickerKind.heartLock => 0.742,
        StickerKind.heartFoil => 0.995,
        StickerKind.heartWreath => 1.069,
        StickerKind.heartOrigami => 1.084,
        StickerKind.heartChoco => 1.068,
        StickerKind.camera => 1.413,
        StickerKind.teddyBear => 0.923,
        StickerKind.tulips => 0.75,
        StickerKind.books => 1.268,
        StickerKind.mug => 1.059,
        StickerKind.memoryJar => 0.67,
        StickerKind.plant => 0.973,
        StickerKind.alarmClock => 0.701,
        StickerKind.basket => 1.089,
        StickerKind.calendar => 1.023,
        StickerKind.lantern => 0.518,
        StickerKind.puppy => 0.852,
        StickerKind.teaCup => 1.369,
        StickerKind.violin => 0.718,
        StickerKind.driedFlowers => 1.072,
        StickerKind.strawHat => 1.406,
        StickerKind.bowSilver => 1.149,
        StickerKind.rose => 0.871,
        StickerKind.pearlEarrings => 2.551,
        StickerKind.candle => 0.945,
        StickerKind.bouquet => 0.918,
        StickerKind.giftBox => 1.008,
        StickerKind.envelope => 1.192,
        StickerKind.featherWhite => 0.805,
        StickerKind.rings => 0.853,
        StickerKind.perfume => 0.591,
        StickerKind.pearlBracelet => 1.144,
        StickerKind.champagne => 0.841,
        StickerKind.cake => 0.934,
        StickerKind.goblet => 0.52,
        StickerKind.heels => 1.077,
        StickerKind.frame => 0.864,
      };

  static StickerKind fromName(String? name) => StickerKind.values.firstWhere(
        (k) => k.name == name,
        orElse: () => StickerKind.heartWhite,
      );
}

/// A free-floating decorative sticker placed on a slide. Position and size are
/// normalized to the canvas so they render identically at any resolution or
/// orientation.
class StickerLayer {
  const StickerLayer({
    required this.id,
    required this.kind,
    this.x = 0.5,
    this.y = 0.5,
    this.widthFraction = 0.22,
    this.rotation = 0.0,
    this.opacity = 1.0,
    this.zOrder = 0,
  });

  final String id;
  final StickerKind kind;
  final double x;             // center-x as fraction of canvas width  (0-1)
  final double y;             // center-y as fraction of canvas height (0-1)
  final double widthFraction; // width as fraction of canvas width
  final double rotation;      // degrees
  final double opacity;       // 0-1
  final int zOrder;

  factory StickerLayer.fromJson(Map<String, dynamic> j) => StickerLayer(
        id: j['id'] as String,
        kind: StickerKindX.fromName(j['kind'] as String?),
        x: (j['x'] as num).toDouble(),
        y: (j['y'] as num).toDouble(),
        widthFraction: (j['widthFraction'] as num? ?? 0.22).toDouble(),
        rotation: (j['rotation'] as num? ?? 0).toDouble(),
        opacity: (j['opacity'] as num? ?? 1.0).toDouble(),
        zOrder: j['zOrder'] as int? ?? 0,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'kind': kind.name,
        'x': x,
        'y': y,
        'widthFraction': widthFraction,
        'rotation': rotation,
        'opacity': opacity,
        'zOrder': zOrder,
      };

  StickerLayer copyWith({
    StickerKind? kind,
    double? x,
    double? y,
    double? widthFraction,
    double? rotation,
    double? opacity,
    int? zOrder,
  }) {
    return StickerLayer(
      id: id,
      kind: kind ?? this.kind,
      x: x ?? this.x,
      y: y ?? this.y,
      widthFraction: widthFraction ?? this.widthFraction,
      rotation: rotation ?? this.rotation,
      opacity: opacity ?? this.opacity,
      zOrder: zOrder ?? this.zOrder,
    );
  }
}
